### ISSUE TITLE
Довести до ума плагин

### ISSUE THREAD

**Issue by thekiba** [FraidZZ/pikabu-user-informer#1]
@FraidZZ, привет.

Предлагаю доделать до ума плагин, реализовать поддержку для Google Chrome, Firefox, Opera (?). Уже сейчас я начал работу над этим, имплементировал Google Chrome и Webpack для удобства сборки. Есть ряд задач, которые было бы здорово доделать.

Сейчас я предлагаю:

- [x]  создать новую ветку `development` для того, чтобы я сделал pull request
- [x]  добавить меня в contributes для совместной разработки

**Comment by FraidZZ** [comment]
@thekiba, привет :)
>> реализовать поддержку для Google Chrome, Firefox, Opera (?).
Так первый и последний работают на вебките - если не считать старую оперу на престо. 

Ветку сделал, собственно.  
>> добавить меня в contributes для совместной разработки
Ты о collaborators?

**Comment by thekiba** [comment]
@FraidZZ, 

> Ты о collaborators?

Ага

**Comment by thekiba** [comment]
Отлично!

Пока development в master не сливай, там есть что доделать.

**Comment by FraidZZ** [comment]
Главное, в мастере оставь непосредственно скрипт информера, если будешь сливать - с него обновляются уже установившие)
